version: '2'

services:
    web:
        image: php:7.2-apache
        restart: always
        ports:
            - 80:80
        volumes:
            - ~/docker/www:/var/www/html
        links:
            - db:db
    db:
        image: mariadb
        restart: always
        volumes:
            - ~/docker/mysql:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8080:80
        links:
            - db:db

# docker-compose up
